import Head from 'next/head'

export default function Home() {
  return (
    <div>
    
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="absolute items-center justify-center p-10 text-6xl font-poppins">
        <div className="relative space-y-5">
          <h1>Hi, I&apos;m</h1>
          <h1>Brendan</h1>
        </div>
      </main>
    </div>
  )
}
